import type { MediaAsset, SectionIntro } from "@/types/content";

export const mediaIntro: SectionIntro = {
  eyebrow: "Наша академія",
  title:
    "Ми виховуємо не лише спортсменів — ми виховуємо характер, дисципліну та повагу.",
  description: "",
};

export const mediaAssets: MediaAsset[] = [
  {
    id: "academy-groundwork",
    title: "Тренування в залі Avangard",
    kind: "photo",
    summary: "Тренувальний момент в академії Avangard Jiu-Jitsu.",
    aspectRatio: "portrait",
    status: "selected",
    statusLabel: "Реальне фото",
    imageSrc: "/media/academy/IMG_5779.jpg",
    objectPosition: "center 48%",
  },
  {
    id: "academy-kids-match",
    title: "Дитячий поєдинок",
    kind: "photo",
    summary: "Юні спортсмени Avangard на змаганнях.",
    aspectRatio: "landscape",
    status: "selected",
    statusLabel: "Реальне фото",
    imageSrc: "/media/academy/53211308790_c1f3220e31_c.jpg",
    objectPosition: "center 48%",
  },
  {
    id: "academy-competition-back",
    title: "Avangard на турнірі",
    kind: "photo",
    summary: "Спортсмен Avangard перед виходом на татамі.",
    aspectRatio: "landscape",
    status: "selected",
    statusLabel: "Реальне фото",
    imageSrc: "/media/academy/3U9A6574-Ulucseno-Um. suma.jpg",
    objectPosition: "center 48%",
  },
  {
    id: "academy-clinch",
    title: "Боротьба в стійці",
    kind: "photo",
    summary: "Технічна робота на тренуванні Avangard.",
    aspectRatio: "portrait",
    status: "selected",
    statusLabel: "Реальне фото",
    imageSrc: "/media/academy/photo_2026-05-22_10-32-12.jpg",
    objectPosition: "center 46%",
  },
  {
    id: "academy-team",
    title: "Команда Avangard",
    kind: "photo",
    summary: "Дитяча команда Avangard після змагань.",
    aspectRatio: "wide",
    status: "selected",
    statusLabel: "Реальне фото",
    imageSrc: "/media/academy/photo_2026-08-08_18-36-21.jpg",
    objectPosition: "center 42%",
  },
  {
    id: "academy-kid-focus",
    title: "Юний спортсмен Avangard",
    kind: "photo",
    summary: "Дитячий виступ на змаганнях.",
    aspectRatio: "wide",
    status: "selected",
    statusLabel: "Реальне фото",
    imageSrc: "/media/academy/IMG_9137.JPG",
    objectPosition: "center 44%",
  },
];
